language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
script:
- platformio run -d firmware -e emonpi_deploy

deploy:
  on:
    repo: openenergymonitor/emonpi
    all_branches: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
  skip_cleanup: true
  provider: releases
  overwrite: true
  api_key:
    secure: "eEkldWBRM6TfN4GJw8FecTNW71CySK3HwuOu/EKtfH8pm3Dk/ynIWyGrZ9fAs9p4e+Nmq7P9hXfRt7rVJdpZ/deo/D/af5+gXZlLgYc8oF18WP7Thsrnu/6oSUZfNTkLVMjjq9BvR6dQU1thA6buh/l+KkhiDhioUiSS7S578t6OMYOKi+A1AIYCrxRUWLu2szY3XxXfFgRYxVlAzbJ+z75FJ1LpyLdg6BiFB8hoosdypwpGle4L93HgGjFln6CxxQOCjxGonX/26IcpuVW15DadiUXU1eaPLC37iuPkfVdRsy6rj4MeT3kL22Nen29w1rbS8XfJ5zHsQ64bFdWZLsYvzGb+eY/mvyLcgwH6T6eTLMK0kSQo36P2JsQM8mmcYshLyZUZerfH2oNvrBHbA5wsEqVk0TlXnGiH3L+i548sc8DR9sUIkcRNhRLyYB0ZVbvoI1ToT8lm+YlP67auKCayaJFh8hCtQI2Eh4Id6v+Y5YuHfht/OHQnfFSfT6DszEQAHtOeZVJ2PzUUDxuyCtXdxNke/Ic2bGT+FSf3Mu6eTpgqzghRzTdKlcgmX7gc58rS2nGHvjLS9h6VtGc3YhObXUfCKeijBAA3v2/za+w4x/VHJQnpOTJYOJBiQbRLUa3cftJ9gUm3ZT8orQbgUhF4J160QUkkE8QfYNeTmFg="
  file: ".pioenvs/emonpi_deploy/firmware.hex"
